## Reshape a tensor

In [1]:
# use of "tensor.view()""
import torch
a = torch.range(1, 16)
print( a.view(4,4).shape )
print( a.view(1,4,4).shape )

torch.Size([4, 4])
torch.Size([1, 4, 4])


/home/samin/environments/py36_baseline/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  This is separate from the ipykernel package so we can avoid doing imports until


In [2]:
a = a.view(1,16)
print('number of rows = {}; number of columns = {}'.format( a.size(0),a.size(1) ) )

number of rows = 1; number of columns = 16


In [3]:
a.view(a.size(0),-1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16.]])

In [93]:
######################################
# compute configuration of Conv layers
######################################
import numpy as np

layer = 3
n_w = 105
n_h = 80
padding = np.array([0,0,0])
filter_ = np.array([8,4,3])
stride = np.array([4,2,1])

import numpy as np
def cal_(n,p,f,s):
    return np.floor((n+(2*p)-f)/s+1)


for itr in range(layer):
    cov_out = np.array([cal_(n_w,padding[itr],filter_[itr],stride[itr]),cal_(n_h,padding[itr],filter_[itr],stride[itr])])
    n_w = cov_out[0]
    n_h = cov_out[1]
    print('output configuration of conv layer {} is = {}'.format(itr+1,cov_out) )
cov_out

output configuration of conv layer 1 is = [25. 19.]
output configuration of conv layer 2 is = [11.  8.]
output configuration of conv layer 3 is = [9. 6.]


array([9., 6.])

In [7]:
n_w = 105
n_h = 80
def conv2d_size_out(size, kernel_size = 5, stride = 2):
    return (size - (kernel_size - 1) - 1) // stride  + 1
convw = conv2d_size_out(conv2d_size_out(conv2d_size_out(n_w)))
convh = conv2d_size_out(conv2d_size_out(conv2d_size_out(n_h)))
print(np.array([convw,convh]))

[10  7]


In [8]:
layer = 3
n_w = 105
n_h = 80
padding = np.array([0,0,0])
filter_ = np.array([5,5,5])
stride = np.array([2,2,2])

import numpy as np
def cal_(n,p,f,s):
    return np.floor((n+(2*p)-f)/s+1)


for itr in range(layer):
    cov_out = np.array([cal_(n_w,padding[itr],filter_[itr],stride[itr]),cal_(n_h,padding[itr],filter_[itr],stride[itr])])
    n_w = cov_out[0]
    n_h = cov_out[1]
    print('output configuration of conv layer {} is = {}'.format(itr+1,cov_out) )
cov_out

output configuration of conv layer 1 is = [51. 38.]
output configuration of conv layer 2 is = [24. 17.]
output configuration of conv layer 3 is = [10.  7.]


array([10.,  7.])

In [9]:
x = torch.range(1, 10*15*64)
x = x.view(10,15,64)

/home/samin/environments/py36_baseline/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


In [10]:
x.view(x.size(0), -1).shape

torch.Size([10, 960])

## torch.max

In [4]:
x = torch.range(1, 32*6)
x = x.view(32,6)

/home/samin/environments/py36_baseline/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


In [6]:
x

tensor([[  1.,   2.,   3.,   4.,   5.,   6.],
        [  7.,   8.,   9.,  10.,  11.,  12.],
        [ 13.,  14.,  15.,  16.,  17.,  18.],
        [ 19.,  20.,  21.,  22.,  23.,  24.],
        [ 25.,  26.,  27.,  28.,  29.,  30.],
        [ 31.,  32.,  33.,  34.,  35.,  36.],
        [ 37.,  38.,  39.,  40.,  41.,  42.],
        [ 43.,  44.,  45.,  46.,  47.,  48.],
        [ 49.,  50.,  51.,  52.,  53.,  54.],
        [ 55.,  56.,  57.,  58.,  59.,  60.],
        [ 61.,  62.,  63.,  64.,  65.,  66.],
        [ 67.,  68.,  69.,  70.,  71.,  72.],
        [ 73.,  74.,  75.,  76.,  77.,  78.],
        [ 79.,  80.,  81.,  82.,  83.,  84.],
        [ 85.,  86.,  87.,  88.,  89.,  90.],
        [ 91.,  92.,  93.,  94.,  95.,  96.],
        [ 97.,  98.,  99., 100., 101., 102.],
        [103., 104., 105., 106., 107., 108.],
        [109., 110., 111., 112., 113., 114.],
        [115., 116., 117., 118., 119., 120.],
        [121., 122., 123., 124., 125., 126.],
        [127., 128., 129., 130., 1

In [5]:
torch.argmax(x,dim=1)

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5])

In [24]:
type(x.max(1)) # is a tuple

tuple

In [28]:
len(x.max(1)) # tuple of two elements

2

In [29]:
# for .max (1) ([maximum along column][maximum value position along the column])
# for .max (0) ([maximum along row][maximum value position along the row])
x.max(1)  

(tensor([  6.,  12.,  18.,  24.,  30.,  36.,  42.,  48.,  54.,  60.,  66.,  72.,
          78.,  84.,  90.,  96., 102., 108., 114., 120., 126., 132., 138., 144.,
         150., 156., 162., 168., 174., 180., 186., 192.]),
 tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5]))

In [30]:
x.max(1)[0] # chooses to give up only max values 

tensor([  6.,  12.,  18.,  24.,  30.,  36.,  42.,  48.,  54.,  60.,  66.,  72.,
         78.,  84.,  90.,  96., 102., 108., 114., 120., 126., 132., 138., 144.,
        150., 156., 162., 168., 174., 180., 186., 192.])

## .detach()

* .detach() detaches the output from the computationnal graph. So no gradient will be backproped along this variable \\

* link: https://discuss.pytorch.org/t/detach-no-grad-and-requires-grad/16915/7

## torch.unsqueeze(obj,dim)

In [80]:
x = torch.range(1, 32*6)
x = x.view(32,6)
print(x.size())

torch.Size([32, 6])


/home/samin/environments/py36_baseline/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


In [90]:
print( x.squeeze().size() )

torch.Size([32, 6])


In [83]:
print(x.squeeze().unsqueeze(0).shape)

torch.Size([1, 32, 6])


In [84]:
print(x.squeeze().unsqueeze(1).shape)

torch.Size([32, 1, 6])


In [85]:
print(x.squeeze().unsqueeze(2).shape)

torch.Size([32, 6, 1])


## torch.gather

In [149]:
t = torch.tensor([[1,2],[3,4]])
print(t)
print( t.gather( 1, torch.tensor([[0,0],[1,0]])) )

tensor([[1, 2],
        [3, 4]])
tensor([[1, 1],
        [4, 3]])


In [146]:
import numpy as np
action = list( np.random.randint(0,6,10) )
action = torch.LongTensor(action)  # ** must be a LongTensor to be used as Mask **
action = action.view(-1,1)
print(action.size())
print(action)

torch.Size([10, 1])
tensor([[2],
        [1],
        [5],
        [2],
        [4],
        [2],
        [2],
        [3],
        [4],
        [4]])


In [147]:
Q = list( np.random.randint(100,200,10*6) )
Q = torch.Tensor(Q).view(10,6)  # shape = ( batch_size 32 , no of actions 6 )
print(Q.size())
print(Q)

torch.Size([10, 6])
tensor([[160., 168., 185., 156., 117., 127.],
        [193., 144., 102., 197., 130., 132.],
        [141., 153., 185., 119., 116., 132.],
        [114., 114., 101., 139., 185., 141.],
        [140., 155., 109., 172., 160., 124.],
        [133., 157., 138., 100., 180., 152.],
        [108., 108., 185., 127., 196., 103.],
        [179., 127., 121., 142., 172., 173.],
        [162., 158., 122., 181., 174., 199.],
        [183., 117., 128., 148., 168., 172.]])


In [148]:
# choose the actions at each state that gives maximum Q and return those Q values
Q.gather(1,action)

tensor([[185.],
        [144.],
        [132.],
        [101.],
        [160.],
        [138.],
        [185.],
        [142.],
        [174.],
        [168.]])

## find done==True is list

* link: https://stackoverflow.com/questions/21448225/getting-indices-of-true-values-in-a-boolean-list

In [163]:
t = [False, False, False, False, True, True, False, True, False, False, False, False, False, False, False, False]
mask = [i for i, x in enumerate(t) if x]
mask

[4, 5, 7]